import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type { Digest, Rule } from './types.js';
import { extractLearnBlock, mergeLearnSections, parseLearnSections, renderLearnBlock, resolveLearnTarget, stripLearnBlock, unifiedDiff, writeLearnBlock, LEARN_BEGIN, LEARN_END } from './writer.js';

const NOW = Date.parse('2026-09-08T12:34:56Z');
let dir: string;

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'vg-writer-'));
});
afterEach(() => fs.rmSync(dir, { recursive: true, force: true }));

function rule(section: string, content: string, tokens = 0, target: Rule['target'] = 'context'): Rule {
  return { target, section, content, confidence: 0.9, evidenceCount: 2, estimatedTokensSaved: tokens, isLoopGuardrail: false, loopOccurrences: 0 };
}

function digest(rules: Rule[]): Digest {
  return {
    sessions: 1,
    toolCalls: 0,
    failures: 0,
    failureRate: 0,
    tokensIn: 0,
    tokensOut: 0,
    loops: [],
    failingCommands: [],
    missingPaths: [],
    recoveries: [],
    corrections: [],
    verbosity: { responses: 0, medianWords: 0, meanWords: 0, bulletsRatio: 0, codeRatio: 0, longOutputRate: 0, interruptRate: 0, fastSkipRate: 0 },
    rules,
    analyzer: 'heuristic',
  };
}

const GOLDEN = `<!-- vg:learn:begin -->
## Learned Patterns
*Auto-generated by \`vg install --learn\` on 2026-09-08 — do not edit manually*

### Loop Guardrails
*~1,234 tokens/session saved*
- \`grep foo | head -50\` was re-run 3x. Fetch the complete output once.

### User Preferences
- User preference: never use npm

<!-- vg:learn:end -->`;

describe('renderLearnBlock', () => {
  it('renders the golden block (context rules first, memory rules after, token annotation only when > 0)', () => {
    const block = renderLearnBlock(digest([rule('User Preferences', '- User preference: never use npm', 0, 'memory'), rule('Loop Guardrails', '- `grep foo | head -50` was re-run 3x. Fetch the complete output once.', 1234)]), { now: NOW });
    expect(block).toBe(GOLDEN);
    expect(block.startsWith(LEARN_BEGIN)).toBe(true);
    expect(block.endsWith(LEARN_END)).toBe(true);
    expect(block).not.toContain('<!-- vg:begin -->');
  });

  it('merges rules that share a section and parses its own output back', () => {
    const block = renderLearnBlock(digest([rule('Environment', '- a', 5), rule('Environment', '- b', 9)]), { now: NOW });
    const sections = parseLearnSections(block);
    expect(sections).toEqual([{ section: 'Environment', content: '- a\n- b', tokensSaved: 9 }]);
    expect(parseLearnSections(GOLDEN)).toEqual([
      { section: 'Loop Guardrails', content: '- `grep foo | head -50` was re-run 3x. Fetch the complete output once.', tokensSaved: 1234 },
      { section: 'User Preferences', content: '- User preference: never use npm', tokensSaved: 0 },
    ]);
    expect(parseLearnSections('no block here')).toEqual([]);
  });
});

describe('block helpers', () => {
  it('extracts, strips and merges sections', () => {
    const file = `# Title\n\nintro\n\n${GOLDEN}\n\ntrailer\n`;
    expect(extractLearnBlock(file)).toBe(GOLDEN);
    expect(extractLearnBlock('nope')).toBeNull();
    expect(extractLearnBlock(`${LEARN_BEGIN} unterminated`)).toBeNull();
    expect(stripLearnBlock(file)).toBe('# Title\n\nintro\n\ntrailer\n');
    expect(stripLearnBlock(`${GOLDEN}\n`)).toBe('');
    expect(stripLearnBlock('untouched')).toBe('untouched');
    const merged = mergeLearnSections([{ section: 'A', content: 'new', tokensSaved: 1 }], [{ section: 'A', content: 'old', tokensSaved: 0 }, { section: 'B', content: 'kept', tokensSaved: 2 }]);
    expect(merged).toEqual([{ section: 'A', content: 'new', tokensSaved: 1 }, { section: 'B', content: 'kept', tokensSaved: 2 }]);
  });

  it('unifiedDiff shows added and removed lines and is empty for identical input', () => {
    expect(unifiedDiff('a\nb\n', 'a\nb\n', 'f')).toBe('');
    const d = unifiedDiff('a\nb\nc\n', 'a\nB\nc\nd\n', 'f');
    expect(d.split('\n').slice(0, 2)).toEqual(['--- f', '+++ f']);
    expect(d).toContain('-b');
    expect(d).toContain('+B');
    expect(d).toContain('+d');
    expect(d).toContain(' a');
    expect(unifiedDiff('x\n'.repeat(5000), 'y', 'big')).toContain('large change');
  });

  it('resolveLearnTarget honours --target, VG_LEARN_TARGET and the CLAUDE.local.md default', () => {
    expect(resolveLearnTarget(undefined, '/p', {})).toBe(path.join('/p', 'CLAUDE.local.md'));
    expect(resolveLearnTarget(undefined, '/p', { VG_LEARN_TARGET: 'AGENTS.md' })).toBe(path.join('/p', 'AGENTS.md'));
    expect(resolveLearnTarget('GEMINI.md', '/p', { VG_LEARN_TARGET: 'AGENTS.md' })).toBe(path.join('/p', 'GEMINI.md'));
    expect(resolveLearnTarget('/abs/x.md', '/p', {})).toBe('/abs/x.md');
  });
});

describe('writeLearnBlock', () => {
  it('creates the target when missing and is idempotent (apply twice → identical bytes)', () => {
    const file = path.join(dir, 'CLAUDE.local.md');
    const first = writeLearnBlock(file, GOLDEN);
    expect(first).toMatchObject({ changed: true, created: true, path: file });
    expect(first.diff).toContain('+<!-- vg:learn:begin -->');
    expect(fs.readFileSync(file, 'utf8')).toBe(`${GOLDEN}\n`);
    expect(fs.readdirSync(dir).filter((f) => f.endsWith('.tmp'))).toEqual([]);
    const second = writeLearnBlock(file, GOLDEN);
    expect(second).toMatchObject({ changed: false, created: false, diff: '' });
    expect(fs.readFileSync(file, 'utf8')).toBe(`${GOLDEN}\n`);
  });

  it('preserves surrounding content, replaces the block in place, and carries forward un-re-emitted sections', () => {
    const file = path.join(dir, 'CLAUDE.md');
    fs.writeFileSync(file, `# Project\n\nHand-written rules.\n\n<!-- vg:begin -->\ninstall block stays\n<!-- vg:end -->\n\n${GOLDEN}\n\nfooter\n`);
    const next = renderLearnBlock(digest([rule('Loop Guardrails', '- new guardrail', 10)]), { now: NOW });
    const res = writeLearnBlock(file, next);
    expect(res.changed).toBe(true);
    const content = fs.readFileSync(file, 'utf8');
    expect(content.startsWith('# Project\n\nHand-written rules.\n\n<!-- vg:begin -->\ninstall block stays\n<!-- vg:end -->\n\n')).toBe(true);
    expect(content.endsWith('\n\nfooter\n')).toBe(true);
    expect(content.split(LEARN_BEGIN)).toHaveLength(2);
    const sections = parseLearnSections(content);
    expect(sections.map((s) => s.section)).toEqual(['Loop Guardrails', 'User Preferences']);
    expect(sections[0].content).toBe('- new guardrail');
    expect(sections[1].content).toBe('- User preference: never use npm');
    expect(content).toContain('on 2026-09-08 —');
    // Re-applying the same next block is a no-op even with the carried section.
    expect(writeLearnBlock(file, next).changed).toBe(false);
  });

  it('appends to a file without a block and never writes on dry-run', () => {
    const file = path.join(dir, 'AGENTS.md');
    fs.writeFileSync(file, '# Agents\n\nsome text\n');
    const dry = writeLearnBlock(file, GOLDEN, { dryRun: true });
    expect(dry.changed).toBe(true);
    expect(dry.content).toBe(`# Agents\n\nsome text\n\n${GOLDEN}\n`);
    expect(fs.readFileSync(file, 'utf8')).toBe('# Agents\n\nsome text\n');
    const missing = path.join(dir, 'nested', 'GROK.md');
    const dryMissing = writeLearnBlock(missing, GOLDEN, { dryRun: true });
    expect(dryMissing).toMatchObject({ changed: true, created: true });
    expect(fs.existsSync(missing)).toBe(false);
    writeLearnBlock(missing, GOLDEN);
    expect(fs.readFileSync(missing, 'utf8')).toBe(`${GOLDEN}\n`);
  });
});
