{{- include "vibgrate.validateDsn" . -}}
{{- if and .Values.dsn (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibgrate.fullname" . }}
  labels:
    {{- include "vibgrate.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecretKey }}: {{ .Values.dsn | quote }}
{{- end }}
